version: 1
labels:
  - label: 'work in progress'
    title: '.*(?i)wip.*'
  - label: 'feature'
    title: '.*(?i)feat.*'
  - label: 'hot fix'
    title: '.*(?i)hotfix.*'
  - label: 'fix'
    title: '.*Fix.*'
  - label: 'enhancement'
    title: '.*(?i)enhancement.*'
  - label: 'refactor'
    title: '.*(?i)refactor.*'
  - label: 'PoC'
    title: '.*(?i)poc.*'
  - label: 'test'
    title: '.*Test.*'
  - label: 'ci'
    title: '^(?i)ci.*'
